<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\Category;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $fiction = Category::where('slug', 'fiction')->first();
        $technology = Category::where('slug', 'technology')->first();
        $business = Category::where('slug', 'business')->first();
        $science = Category::where('slug', 'science')->first();
        $education = Category::where('slug', 'education')->first();
        $history = Category::where('slug', 'history')->first();

        $books = [
            [
                'category_id' => $fiction?->id,
                'title' => 'The Silent Harbor',
                'slug' => 'the-silent-harbor',
                'author' => 'Mara Ellison',
                'isbn' => '9781000000001',
                'description' => 'A mystery novel set in a quiet coastal town.',
                'price' => 499.00,
                'stock' => 30,
                'cover_image' => null,
                'published_at' => '2024-01-15',
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'category_id' => $technology?->id,
                'title' => 'Laravel for Builders',
                'slug' => 'laravel-for-builders',
                'author' => 'Daniel Cruz',
                'isbn' => '9781000000002',
                'description' => 'A practical Laravel guide for full-stack application building.',
                'price' => 799.00,
                'stock' => 25,
                'cover_image' => null,
                'published_at' => '2024-05-10',
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'category_id' => $business?->id,
                'title' => 'Startup Basics',
                'slug' => 'startup-basics',
                'author' => 'Leah Romero',
                'isbn' => '9781000000003',
                'description' => 'An introduction to starting and managing a small business.',
                'price' => 650.00,
                'stock' => 18,
                'cover_image' => null,
                'published_at' => '2023-11-20',
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'category_id' => $technology?->id,
                'title' => 'Clean Code Essentials',
                'slug' => 'clean-code-essentials',
                'author' => 'Iris Bennett',
                'isbn' => '9781000000004',
                'description' => 'Writing cleaner, more maintainable code in modern applications.',
                'price' => 720.00,
                'stock' => 20,
                'cover_image' => null,
                'published_at' => '2024-03-11',
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'category_id' => $science?->id,
                'title' => 'Understanding Physics',
                'slug' => 'understanding-physics',
                'author' => 'Ramon Velasquez',
                'isbn' => '9781000000005',
                'description' => 'A beginner-friendly guide to fundamental physics concepts.',
                'price' => 580.00,
                'stock' => 22,
                'cover_image' => null,
                'published_at' => '2022-08-14',
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'category_id' => $education?->id,
                'title' => 'Study Smarter',
                'slug' => 'study-smarter',
                'author' => 'Clara Mendoza',
                'isbn' => '9781000000006',
                'description' => 'Methods for learning faster and remembering more.',
                'price' => 430.00,
                'stock' => 35,
                'cover_image' => null,
                'published_at' => '2023-09-01',
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'category_id' => $history?->id,
                'title' => 'World History in Focus',
                'slug' => 'world-history-in-focus',
                'author' => 'Antonio Reyes',
                'isbn' => '9781000000007',
                'description' => 'Major events and turning points in world history.',
                'price' => 610.00,
                'stock' => 16,
                'cover_image' => null,
                'published_at' => '2021-06-19',
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'category_id' => $fiction?->id,
                'title' => 'Midnight Train',
                'slug' => 'midnight-train',
                'author' => 'Elena Ford',
                'isbn' => '9781000000008',
                'description' => 'A suspense story about secrets uncovered on a late-night trip.',
                'price' => 540.00,
                'stock' => 28,
                'cover_image' => null,
                'published_at' => '2024-02-18',
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'category_id' => $business?->id,
                'title' => 'Marketing That Works',
                'slug' => 'marketing-that-works',
                'author' => 'Paolo Santos',
                'isbn' => '9781000000009',
                'description' => 'Practical digital marketing strategies for modern businesses.',
                'price' => 690.00,
                'stock' => 14,
                'cover_image' => null,
                'published_at' => '2024-04-25',
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'category_id' => $technology?->id,
                'title' => 'Database Design Made Simple',
                'slug' => 'database-design-made-simple',
                'author' => 'Gina Flores',
                'isbn' => '9781000000010',
                'description' => 'A practical introduction to schema design and data modeling.',
                'price' => 760.00,
                'stock' => 24,
                'cover_image' => null,
                'published_at' => '2023-12-10',
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'category_id' => $science?->id,
                'title' => 'Biology Basics',
                'slug' => 'biology-basics',
                'author' => 'Noel Caballero',
                'isbn' => '9781000000011',
                'description' => 'Core concepts in biology for beginners and students.',
                'price' => 560.00,
                'stock' => 21,
                'cover_image' => null,
                'published_at' => '2022-11-09',
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'category_id' => $education?->id,
                'title' => 'Exam Ready Notes',
                'slug' => 'exam-ready-notes',
                'author' => 'Jean Alvarez',
                'isbn' => '9781000000012',
                'description' => 'A guide to creating organized and effective study notes.',
                'price' => 390.00,
                'stock' => 40,
                'cover_image' => null,
                'published_at' => '2024-01-05',
                'status' => 'active',
                'is_featured' => true,
            ],
            [
                'category_id' => $history?->id,
                'title' => 'Ancient Civilizations',
                'slug' => 'ancient-civilizations',
                'author' => 'Loren Diaz',
                'isbn' => '9781000000013',
                'description' => 'An overview of the world’s early great civilizations.',
                'price' => 630.00,
                'stock' => 17,
                'cover_image' => null,
                'published_at' => '2020-10-30',
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'category_id' => $fiction?->id,
                'title' => 'The Last Lantern',
                'slug' => 'the-last-lantern',
                'author' => 'Harper Quinn',
                'isbn' => '9781000000014',
                'description' => 'A dramatic story of family, hope, and survival.',
                'price' => 515.00,
                'stock' => 23,
                'cover_image' => null,
                'published_at' => '2023-07-17',
                'status' => 'active',
                'is_featured' => false,
            ],
            [
                'category_id' => $technology?->id,
                'title' => 'API Design Handbook',
                'slug' => 'api-design-handbook',
                'author' => 'Victor Pascual',
                'isbn' => '9781000000015',
                'description' => 'Best practices for designing practical and scalable APIs.',
                'price' => 840.00,
                'stock' => 19,
                'cover_image' => null,
                'published_at' => '2024-06-01',
                'status' => 'active',
                'is_featured' => true,
            ],
        ];

        foreach ($books as $book) {
            if ($book['category_id']) {
                Book::updateOrCreate(
                    ['slug' => $book['slug']],
                    $book
                );
            }
        }
    }
}
